// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBARGwCPVIllxyyPP11GN-IgKCdPagUyys',
    appId: '1:740295515224:web:77f4e3c7a8163d2e22be2d',
    messagingSenderId: '740295515224',
    projectId: 'meal-recipes-notebook',
    authDomain: 'meal-recipes-notebook.firebaseapp.com',
    storageBucket: 'meal-recipes-notebook.appspot.com',
    measurementId: 'G-NXFVEH427P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMxlm8qbDuULxNTMYvduRT7rxqFOv1w1Y',
    appId: '1:740295515224:android:cb1e01f2eb5bf6ba22be2d',
    messagingSenderId: '740295515224',
    projectId: 'meal-recipes-notebook',
    storageBucket: 'meal-recipes-notebook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB527coqiC60louPTnJc3wuR01NPgEidY',
    appId: '1:740295515224:ios:91b92ad42cd786e322be2d',
    messagingSenderId: '740295515224',
    projectId: 'meal-recipes-notebook',
    storageBucket: 'meal-recipes-notebook.appspot.com',
    iosClientId: '740295515224-g4revd2kcdu8u6k90i3t791afg1o7lcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeNotebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB527coqiC60louPTnJc3wuR01NPgEidY',
    appId: '1:740295515224:ios:91b92ad42cd786e322be2d',
    messagingSenderId: '740295515224',
    projectId: 'meal-recipes-notebook',
    storageBucket: 'meal-recipes-notebook.appspot.com',
    iosClientId: '740295515224-g4revd2kcdu8u6k90i3t791afg1o7lcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeNotebook',
  );
}
